//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_WEB2_ASP.NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh_SanPham
    {
        public int ID { get; set; }
        public string AnhChiTiet { get; set; }
        public Nullable<int> idSanPham { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
