//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_WEB2_ASP.NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ChiTiet_HoaDon = new HashSet<ChiTiet_HoaDon>();
            this.DiaChiGiaoHangs = new HashSet<DiaChiGiaoHang>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_HoaDon> ChiTiet_HoaDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiaChiGiaoHang> DiaChiGiaoHangs { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TrangThai_HoaDon TrangThai_HoaDon { get; set; }
    }
}
