//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_WEB2_ASP.NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTiet_HoaDon = new HashSet<ChiTiet_HoaDon>();
            this.HinhAnh_SanPham = new HashSet<HinhAnh_SanPham>();
            this.SanPhamYeuThiches = new HashSet<SanPhamYeuThich>();
        }
    
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> Gia { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<int> idLoaiSanPham { get; set; }
        public Nullable<int> idDanhMuc { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> BiXoa { get; set; }
        public Nullable<int> idNhaSanXuat { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<bool> KhuyenMai { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_HoaDon> ChiTiet_HoaDon { get; set; }
        public virtual Danh_Muc Danh_Muc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh_SanPham> HinhAnh_SanPham { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamYeuThich> SanPhamYeuThiches { get; set; }
    }
}
